const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http');
const encode=v=>v==null?{nullValue:null}:typeof v==='string'?{stringValue:v}:typeof v==='boolean'?{booleanValue:v}:typeof v==='number'?{doubleValue:v}:Array.isArray(v)?{arrayValue:{values:v.map(encode)}}:{mapValue:{fields:Object.fromEntries(Object.entries(v).map(([k,x])=>[k,encode(x)]))}};
const decode=v=>'stringValue'in v?v.stringValue:'booleanValue'in v?v.booleanValue:'doubleValue'in v?v.doubleValue:'integerValue'in v?Number(v.integerValue):'arrayValue'in v?(v.arrayValue.values||[]).map(decode):'mapValue'in v?Object.fromEntries(Object.entries(v.mapValue.fields||{}).map(([k,x])=>[k,decode(x)])):null;
const seed=()=>({payday:'2026-10-09',paycheck:1000,frequency:'biweekly',primaryJobName:'Test job',bills:[{id:'rent',name:'Rent',amount:800,dueMode:'monthly',dueDay:0,splitMode:'even',overdue:0}],version:108,setupReviewSeen:true,additionalPaychecks:[],paycheckOverrides:{},cushion:100,extraIncome:0,strategy:'balanced',paycheckHistory:[],paymentHistory:[]});
async function serve(){const server=http.createServer((req,res)=>{const path=req.url.split('?')[0];if(!['/','/index.html','/cloud-sync.js','/service-worker.js','/manifest.webmanifest','/checkstride-logo.svg','/icon-192.png','/icon-512.png','/apple-touch-icon.png'].includes(path)){res.writeHead(404).end();return}res.setHeader('Content-Type',path.endsWith('.png')?'image/png':path.endsWith('.js')?'application/javascript':path.endsWith('.svg')?'image/svg+xml':path.endsWith('.webmanifest')?'application/manifest+json':'text/html');res.end(fs.readFileSync('.'+(path==='/'?'/index.html':path)))});await new Promise(r=>server.listen(0,'127.0.0.1',r));return {server,url:`http://127.0.0.1:${server.address().port}`}}
async function mock(context){let records={A:seed(),B:{...seed(),bills:[{...seed().bills[0],name:'B bill',amount:90}]}},versions={A:1,B:1},writes=[],fail=false,expire=false,refreshes=0,refreshFail=false,resetFail=false;
 await context.route('https://**/*',async route=>{const req=route.request(),url=req.url();
  if(url.includes('securetoken.googleapis.com')){refreshes++;if(refreshFail==='network')return route.abort('failed');if(refreshFail)return route.fulfill({status:400,json:{error:{message:'TOKEN_EXPIRED'}}});const uid=new URLSearchParams(req.postData()).get('refresh_token').endsWith('B')?'B':'A';return route.fulfill({json:{id_token:'test-'+uid,refresh_token:'refresh-'+uid,user_id:uid}});}
  if(url.includes('identitytoolkit.googleapis.com')){const body=req.postDataJSON();if(body.requestType==='PASSWORD_RESET'&&resetFail)return route.abort('failed');const uid=body.email?.startsWith('b@')?'B':'A';return route.fulfill({json:{idToken:'test-'+uid,refreshToken:'refresh-'+uid,localId:uid,email:body.email}})}
  if(url.includes('firestore.googleapis.com')){const commit=req.method()==='POST'&&url.endsWith('documents:commit');const write=commit?req.postDataJSON().writes[0]:null;const uid=(commit?write.update.name:url).match(/users\/([^/]+)/)[1];if(req.headers().authorization!=='Bearer test-'+uid)return route.fulfill({status:403,json:{}});
   if(commit||req.method()==='PATCH'){writes.push(uid);if(expire){expire=false;return route.fulfill({status:401,json:{}})}if(fail)return route.abort('failed');const condition=commit?write.currentDocument.updateTime:new URL(url).searchParams.get('currentDocument.updateTime');if(condition!=='v'+versions[uid])return route.fulfill({status:409,json:{}});records[uid]=Object.fromEntries(Object.entries(commit?write.update.fields:req.postDataJSON().fields).map(([k,v])=>[k,decode(v)]));versions[uid]++;await new Promise(r=>setTimeout(r,75));}
   if(commit)return route.fulfill({json:{writeResults:[{updateTime:'v'+versions[uid]}]}});return route.fulfill({json:{updateTime:'v'+versions[uid],fields:Object.fromEntries(Object.entries(records[uid]).map(([k,v])=>[k,encode(v)]))}});
  }return route.abort();
 });return {records,writes,setFail:v=>fail=v,expireNextWrite:()=>expire=true,getRefreshes:()=>refreshes,setRefreshFailure:v=>refreshFail=v,setResetFailure:v=>resetFail=v};}
module.exports={serve,mock,seed};
