const test=require('node:test'),assert=require('node:assert/strict');const {chromium}=require('playwright');const {serve,mock}=require('./browser-harness.cjs');
async function setup(run){const {server,url}=await serve();const browser=await chromium.launch({headless:true});try{const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,serviceWorkers:'block'});const backend=await mock(context);const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await run(page,backend);assert.deepEqual(errors,[]);}finally{await browser.close();await new Promise(r=>server.close(r))}}
const login=async page=>{await page.locator('#email').fill('a@example.test');await page.locator('#password').fill('fake-only-password');await page.locator('#authSubmit').click();await page.locator('#appView').waitFor({state:'visible'});};
const saved=page=>page.waitForFunction(()=>document.getElementById('cloudStatus').textContent==='Saved');
const click=async(page,selector)=>{await page.locator(selector).click()};
test('auth validation, keyboard submit, password visibility and recovery request',()=>setup(async(page,backend)=>{
 await click(page,'#authSubmit');assert.match(await page.locator('#authMsg').innerText(),/email/);await page.locator('#email').fill('invalid');await click(page,'#resetPassword');assert.match(await page.locator('#authMsg').innerText(),/valid email/);await click(page,'#forgotUsername');assert.match(await page.locator('#authMsg').innerText(),/email/i);
 await page.locator('#email').fill('a@example.test');await click(page,'#resetPassword');await page.waitForFunction(()=>document.getElementById('authMsg').textContent.includes('reset email sent'));assert.match(await page.locator('#authMsg').innerText(),/reset email sent/i);await page.locator('#password').fill('fake-only-password');await click(page,'#togglePassword');assert.equal(await page.locator('#password').getAttribute('type'),'text');await click(page,'#togglePassword');assert.equal(await page.locator('#password').getAttribute('type'),'password');await click(page,'#tabSignup');await page.locator('#password').fill('123');await click(page,'#authSubmit');assert.match(await page.locator('#authMsg').innerText(),/6 characters/);await click(page,'#tabLogin');await page.locator('#password').fill('fake-only-password');await page.locator('#password').press('Enter');await page.locator('#appView').waitFor({state:'visible'});
}));
test('all primary destinations, filters, plan details, scenarios, goals and job management',()=>setup(async(page,backend)=>{
 page.on('dialog',d=>d.accept());await login(page);
 for(const period of await page.locator('[data-home-period]').evaluateAll(xs=>xs.map(x=>x.dataset.homePeriod))){await click(page,`[data-home-period="${period}"]`)}await click(page,'#homePeriodHeader');await click(page,'#homePeriodHeader');
 await click(page,'[data-page="bills"]');for(const view of await page.locator('[data-bills-view]').evaluateAll(xs=>xs.map(x=>x.dataset.billsView)))await click(page,`[data-bills-view="${view}"]`);for(const filter of await page.locator('[data-bill-filter]').evaluateAll(xs=>xs.map(x=>x.dataset.billFilter)))await click(page,`[data-bill-filter="${filter}"]`);await click(page,'[data-bill-filter="all"]');
 await click(page,'[data-page="coach"]');for(const view of await page.locator('[data-plan-view]').evaluateAll(xs=>xs.map(x=>x.dataset.planView)))await click(page,`[data-plan-view="${view}"]`);
 for(const detail of ['recommendation','scenario','complete','advanced']){await click(page,`[data-plan-detail="${detail}"]`);assert.ok(await page.locator('#planDetailBack').isVisible());if(detail==='scenario'){await page.locator('#scenarioPurchase').fill('25.01');await page.locator('#scenarioIncome').fill('-100');await page.locator('#scenarioBill').fill('10');await click(page,'#runScenario');assert.ok((await page.locator('#scenarioResult').innerText()).length>0);}await click(page,'#planDetailBack')}
 await click(page,'[data-page="more"]');for(const destination of ['income','goals','learning','account']){await click(page,`[data-more-destination="${destination}"]`);assert.ok(await page.locator('#moreBackButton').isVisible());await click(page,'#moreBackButton');}
 await click(page,'[data-more-destination="goals"]');await page.locator('#goalName').fill('Emergency fund');await page.locator('#goalTarget').fill('500.01');await page.locator('#goalSaved').fill('600');await click(page,'#saveGoal');assert.match(await page.locator('#goalMsg').innerText(),/greater/);await page.locator('#goalSaved').fill('10.01');await click(page,'#saveGoal');await saved(page);assert.equal(backend.records.A.smartMemory.goals[0].target,500.01);await click(page,'#removeGoal');assert.equal(backend.records.A.smartMemory.goals.length,1);await click(page,'#removeGoal');await saved(page);assert.equal(backend.records.A.smartMemory.goals.length,0);
 await click(page,'#moreBackButton');await click(page,'[data-more-destination="income"]');await click(page,'#showAddIncomeJob');await page.locator('#editJobName').fill('Second job');await page.locator('#editJobPayday').fill('2026-10-15');await page.locator('#editJobPaycheck').fill('123.45');await page.locator('#editJobFrequency').selectOption('monthly');await click(page,'#saveEditedJob');await saved(page);assert.equal(backend.records.A.additionalPaychecks[0].paycheck,123.45);await page.locator('#incomeJobOverview').waitFor({state:'visible'});const id=backend.records.A.additionalPaychecks[0].id;await click(page,`button[data-income-open="${id}"]`);await click(page,'#incomeCalendarNext');await click(page,'#incomeCalendarPrev');await click(page,'#incomeCalendarToday');await click(page,'#editIncomeJobSettings');await page.locator('#editJobPaycheck').fill('130.25');await click(page,'#saveEditedJob');await saved(page);assert.equal(backend.records.A.additionalPaychecks[0].paycheck,130.25);await page.locator('#incomeScheduleView').waitFor({state:'visible'});await click(page,'#editIncomeJobSettings');await click(page,'#removeEditedJob');await saved(page);assert.equal(backend.records.A.additionalPaychecks.length,0);
}));
test('bill add, due/split menus, paid toggle, deletion and cloud persistence',()=>setup(async(page,backend)=>{
 await login(page);await click(page,'[data-page="bills"]');await click(page,'#showAddBill');await page.locator('#billName').fill('Power');await page.locator('#billAmount').fill('75.25');await page.locator('#billDueMode').selectOption('date');await page.locator('#billDay').fill('31');await page.locator('#billSplitMode').selectOption('even');await page.locator('#billPriority').selectOption('critical');await click(page,'#addBill');await saved(page);const bill=backend.records.A.bills.find(x=>x.name==='Power');assert.ok(bill,JSON.stringify({bills:backend.records.A.bills,message:await page.locator('#billMsg').textContent(),status:await page.locator('#cloudStatus').textContent()}));assert.equal(bill.amount,75.25);await page.locator('#billsOverviewView').waitFor({state:'visible'});await click(page,`[data-bill-open="${bill.id}"]`);await click(page,'#billDetailsPaid');await saved(page);assert.ok(backend.records.A.paymentHistory.some(x=>x.billId===bill.id));await click(page,'#billDetailsPaid');await saved(page);assert.ok(!backend.records.A.paymentHistory.some(x=>x.billId===bill.id));await click(page,'#billDetailsRemove');assert.ok(backend.records.A.bills.some(x=>x.id===bill.id));await click(page,'#billDetailsRemove');await saved(page);assert.ok(!backend.records.A.bills.some(x=>x.id===bill.id));await page.reload();await page.locator('#appView').waitFor({state:'visible'});assert.ok(!backend.records.A.bills.some(x=>x.id===bill.id));
}));
test('cloud IDs and names render as inert text rather than injected attributes',()=>setup(async(page,backend)=>{
 const malicious='rent" onclick="window.injected=true" data-extra="';backend.records.A.bills[0].id=malicious;backend.records.A.bills[0].name='<img src=x onerror="window.injected=true">';await login(page);await click(page,'[data-page="bills"]');const row=page.locator('[data-bill-open]').first();assert.equal(await row.getAttribute('data-bill-open'),malicious);assert.equal(await row.getAttribute('onclick'),null);await row.click();assert.equal(await page.evaluate(()=>window.injected),undefined);assert.equal(await page.locator('#billList img').count(),0);
}));
test('expired save token refreshes once; permanent expiration preserves pending changes',()=>setup(async(page,backend)=>{
 await login(page);backend.expireNextWrite();await page.evaluate(()=>window.checkstrideEditBill('rent'));await page.locator('#billAmount').fill('900.25');await page.evaluate(()=>window.checkstrideSubmitBill());await saved(page);assert.equal(backend.getRefreshes(),1);assert.equal(backend.records.A.bills[0].amount,900.25);
 backend.setRefreshFailure(true);backend.expireNextWrite();await page.evaluate(()=>window.checkstrideEditBill('rent'));await page.locator('#billAmount').fill('901.25');await page.evaluate(()=>window.checkstrideSubmitBill());await page.waitForFunction(()=>document.getElementById('cloudStatus').textContent.includes('sign in again'));assert.equal(backend.records.A.bills[0].amount,900.25);assert.ok(await page.evaluate(()=>localStorage.getItem('checkstride_pending_v1:A')));
}));
test('malformed cloud records cannot trigger a destructive normalization save',()=>setup(async(page,backend)=>{
 backend.records.A.bills.push({name:'Corrupted amount',amount:-5});await page.locator('#email').fill('a@example.test');await page.locator('#password').fill('fake-only-password');await click(page,'#authSubmit');await page.waitForFunction(()=>document.getElementById('authMsg').textContent.includes('invalid records'));assert.equal(backend.writes.length,0);assert.equal(backend.records.A.bills[1].amount,-5);assert.ok(!(await page.locator('#appView').isVisible()));
}));
test('network failure during recovery never claims an email was sent',()=>setup(async(page,backend)=>{
 backend.setResetFailure(true);await page.locator('#email').fill('a@example.test');await click(page,'#resetPassword');await page.waitForFunction(()=>document.getElementById('authMsg').textContent.includes('Could not send'));assert.ok(!(await page.locator('#resetPassword').isDisabled()));
}));
test('swipes cross all tabs and return to Today; vertical swipes do not navigate',()=>setup(async(page)=>{
 await login(page);const swipe=async(dx,dy=0)=>page.evaluate(({dx,dy})=>{const el=document.getElementById('appView');el.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerType:'touch',clientX:200,clientY:300,pointerId:1}));el.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,pointerType:'touch',clientX:200+dx,clientY:300+dy,pointerId:1}));},{dx,dy});
 for(const tab of ['bills','coach','more']){await swipe(-100);assert.ok(await page.locator(`[data-page="${tab}"]`).evaluate(x=>x.classList.contains('active')))}for(const tab of ['coach','bills','home']){await swipe(100);assert.ok(await page.locator(`[data-page="${tab}"]`).evaluate(x=>x.classList.contains('active')))}await swipe(10,100);assert.ok(await page.locator('[data-page="home"]').evaluate(x=>x.classList.contains('active')));
}));
test('completed monthly paychecks retain January 31 anchor through February; history is never truncated',()=>setup(async(page,backend)=>{
 backend.records.A.payday='2026-01-31';backend.records.A.frequency='monthly';backend.records.A.paycheckHistory=Array.from({length:65},(_,i)=>({date:'2025-01-01',income:1000,actualLeft:100,id:'history-'+i}));await login(page);await click(page,'[data-page="coach"]');await click(page,'[data-plan-detail="complete"]');
 for(const want of ['2026-02-28','2026-03-31']){await page.locator('#actualIncome').fill('1000');await page.locator('#actualExtra').fill('0');await page.locator('#unexpectedSpend').fill('0');await page.locator('#actualLeft').fill('100');await click(page,'#completePaycheck');await saved(page);assert.equal(backend.records.A.payday,want)}assert.equal(backend.records.A.paycheckHistory.length,67);assert.equal(backend.records.A.paycheckHistory[0].id,'history-0');await page.reload();await page.locator('#appView').waitFor({state:'visible'});assert.equal(backend.records.A.primaryPaydayAnchor,31);
}));
test('plan approvals, rebuilding, feedback and coach mode remain reachable through navigation',()=>setup(async(page,backend)=>{
 await login(page);await click(page,'[data-page="coach"]');await click(page,'[data-plan-detail="recommendation"]');await click(page,'#planWorked');await saved(page);assert.equal(backend.records.A.smartMemory.planWins,1);await click(page,'#planMissed');await saved(page);assert.equal(backend.records.A.smartMemory.planMisses,1);await click(page,'#planDetailBack');await click(page,'[data-plan-detail="advanced"]');await click(page,'#approvePlan');await saved(page);assert.ok(backend.records.A.smartMemory.autonomousPlan.approvedAt);await click(page,'#rebuildPlan');await saved(page);assert.ok(!backend.records.A.smartMemory.autonomousPlan.approvedAt);await click(page,'#strideSystemDropdown > summary');await click(page,'#toggleCoachMode');await saved(page);assert.equal(backend.records.A.smartMemory.coachMode,'auto-draft');await click(page,'#toggleCoachMode');await saved(page);assert.equal(backend.records.A.smartMemory.coachMode,'guided');
}));
test('goal form never announces a cloud save while writes are failing',()=>setup(async(page,backend)=>{
 await login(page);await click(page,'[data-page="more"]');await click(page,'[data-more-destination="goals"]');await page.locator('#goalName').fill('Offline goal');await page.locator('#goalTarget').fill('100');await page.locator('#goalSaved').fill('1');backend.setFail(true);await click(page,'#saveGoal');await page.waitForFunction(()=>document.getElementById('goalMsg').textContent.includes('not synced'));assert.ok(!(await page.locator('#goalMsg').innerText()).includes('saved to cloud'));assert.ok(!backend.records.A.smartMemory?.goals?.length);assert.ok(await page.evaluate(()=>localStorage.getItem('checkstride_pending_v1:A')));
}));
test('deleting a bill retains historical payment records',()=>setup(async(page,backend)=>{
 backend.records.A.paymentHistory=[{id:'old-payment',billId:'rent',billName:'Rent',amount:800,date:'2025-01-01T12:00:00Z',monthKey:'month:2025-01',periodKey:null}];await login(page);await click(page,'[data-page="bills"]');await click(page,'[data-bill-open="rent"]');await click(page,'#billDetailsRemove');await click(page,'#billDetailsRemove');await saved(page);assert.equal(backend.records.A.bills.length,0);assert.equal(backend.records.A.paymentHistory[0].id,'old-payment');
}));
test('empty plans are usable; Account B session restores without loading Account A',()=>setup(async(page,backend)=>{
 backend.records.A.bills=[];backend.records.A.payday='';backend.records.A.paycheck=0;await login(page);await click(page,'[data-page="bills"]');assert.match(await page.locator('#billList').innerText(),/No bills/);await click(page,'[data-page="coach"]');await click(page,'[data-plan-detail="scenario"]');await click(page,'#runScenario');assert.match(await page.locator('#scenarioResult').innerText(),/setup/i);await page.evaluate(()=>document.getElementById('logout').click());await page.locator('#authView').waitFor({state:'visible'});await page.locator('#email').fill('b@example.test');await page.locator('#password').fill('fake-only-password');await click(page,'#authSubmit');await page.locator('#appView').waitFor({state:'visible'});await page.reload();await page.locator('#appView').waitFor({state:'visible'});await click(page,'[data-page="bills"]');assert.match(await page.locator('#billList').innerText(),/B bill/);assert.ok(!backend.writes.includes('A'));
}));
test('cloud conflict recovery preserves both copies and returns to an editable plan',()=>setup(async(page,backend)=>{
 await page.evaluate(()=>localStorage.setItem('checkstride_pending_v1:A',JSON.stringify({base:'v0',data:{bills:[{id:'rent',name:'Rent',amount:901.25}]}})));await page.locator('#email').fill('a@example.test');await page.locator('#password').fill('fake-only-password');await click(page,'#authSubmit');await page.locator('#keepCloudPlan').waitFor({state:'visible'});assert.equal(backend.writes.length,0);const download=page.waitForEvent('download');await click(page,'#downloadConflictCopy');assert.equal((await download).suggestedFilename(),'checkstride-recovery.json');await click(page,'#keepCloudPlan');await page.locator('#appView').waitFor({state:'visible'});assert.equal(backend.records.A.bills[0].amount,800);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('checkstride_recovery_v1:A'))[0].data.bills[0].amount),901.25);await page.evaluate(()=>window.checkstrideEditBill('rent'));await page.locator('#billAmount').fill('810.25');await page.evaluate(()=>window.checkstrideSubmitBill());await saved(page);assert.equal(backend.records.A.bills[0].amount,810.25);await click(page,'[data-page="more"]');await click(page,'[data-more-destination="account"]');assert.ok(await page.locator('#downloadRecoveryCopies').isVisible());
}));
test('first-job onboarding and paycheck amount overrides complete without data loss',()=>setup(async(page,backend)=>{
 backend.records.A.bills=[];backend.records.A.payday='';backend.records.A.paycheck=0;backend.records.A.setupReviewSeen=false;await login(page);await click(page,'#setupPaycheckStep');await click(page,'#showAddIncomeJob');await page.locator('#editJobName').fill('First job');await page.locator('#editJobPayday').fill('2026-10-09');await page.locator('#editJobPaycheck').fill('400.25');await page.locator('#editJobFrequency').selectOption('weekly');await click(page,'#saveEditedJob');await saved(page);assert.equal(backend.records.A.paycheck,400.25);assert.equal(backend.records.A.additionalPaychecks.length,0);await page.locator('#incomeJobOverview').waitFor({state:'visible'});await click(page,'button[data-income-open="primary"]');const date=await page.locator('[data-payday-date]').first().getAttribute('data-payday-date');await page.locator('[data-payday-date]').first().click();await page.locator('#selectedPaydayAmount').fill('399.99');await click(page,'#saveSelectedPayday');await saved(page);assert.equal(backend.records.A.paycheckOverrides['primary|'+date],399.99);await click(page,'#resetSelectedPayday');await saved(page);assert.ok(!Object.hasOwn(backend.records.A.paycheckOverrides,'primary|'+date));await click(page,'#incomeScheduleBack');await click(page,'[data-page="home"]');await click(page,'#setupBillsStep');await page.locator('#billAmount').waitFor({state:'visible'});await page.locator('#billName').fill('First bill');await page.locator('#billAmount').fill('25.01');await click(page,'#addBill');await saved(page);assert.ok(backend.records.A.bills.some(x=>x.name==='First bill'));await click(page,'[data-page="home"]');await click(page,'#setupReviewStep');await saved(page);assert.equal(backend.records.A.setupReviewSeen,true);await click(page,'#homeOpenPlan');assert.ok(await page.locator('[data-page="coach"]').evaluate(x=>x.classList.contains('active')));
}));
test('unknown income fields and retired-source overrides survive loading and saving',()=>setup(async(page,backend)=>{
 backend.records.A.paycheckOverrides={'retired-source|2026-10-09':123.45};backend.records.A.additionalPaychecks=[{id:'second',name:'Second source',payday:'2026-10-15',paycheck:80,frequency:'monthly',futureField:{note:'Keep this field'}}];await login(page);await page.evaluate(()=>window.checkstrideEditBill('rent'));await page.locator('#billAmount').fill('805.25');await page.evaluate(()=>window.checkstrideSubmitBill());await saved(page);assert.equal(backend.records.A.paycheckOverrides['retired-source|2026-10-09'],123.45);assert.equal(backend.records.A.additionalPaychecks[0].futureField.note,'Keep this field');
}));
test('startup network recovery retries safely; expired restoration keeps pending copies',()=>setup(async(page,backend)=>{
 await login(page);backend.setRefreshFailure('network');await page.reload();await page.locator('#loadingRetry').waitFor({state:'visible'});assert.ok(await page.evaluate(()=>localStorage.getItem('checkstride_rest_session')));backend.setRefreshFailure(false);await click(page,'#loadingRetry');await page.locator('#appView').waitFor({state:'visible'});await page.evaluate(()=>localStorage.setItem('checkstride_pending_v1:A',JSON.stringify({base:'v1',data:{bills:[{id:'rent',name:'Rent',amount:901.25}]}})));backend.setRefreshFailure(true);await page.reload();await page.locator('#authView').waitFor({state:'visible'});assert.equal(await page.evaluate(()=>localStorage.getItem('checkstride_rest_session')),null);assert.ok(await page.evaluate(()=>localStorage.getItem('checkstride_pending_v1:A')));assert.equal(backend.records.A.bills[0].amount,800);
}));
test('bill and income cancel/back controls discard only unsubmitted form edits',()=>setup(async(page,backend)=>{
 await login(page);await page.evaluate(()=>window.checkstrideEditBill('rent'));await page.locator('#billAmount').fill('999');await click(page,'#cancelBillEdit');assert.equal(backend.records.A.bills[0].amount,800);await click(page,'#showAddBill');await page.locator('#billName').fill('Unsubmitted');await click(page,'#billFormBack');assert.equal(backend.records.A.bills.length,1);await click(page,'[data-page="more"]');await click(page,'[data-more-destination="income"]');await click(page,'button[data-income-settings="primary"]');await page.locator('#editJobPaycheck').fill('999');await click(page,'#cancelEditedJob');assert.equal(backend.records.A.paycheck,1000);await click(page,'button[data-income-open="primary"]');await click(page,'#incomeScheduleBack');assert.ok(await page.locator('#incomeJobOverview').isVisible());assert.equal(backend.writes.length,0);
}));
test('device backup failure cannot silently discard unsynced edits on sign-out',()=>setup(async(page,backend)=>{
 await login(page);await page.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key.startsWith('checkstride_pending_v1:'))throw new DOMException('quota','QuotaExceededError');return original.call(this,key,value)}});await page.evaluate(()=>window.checkstrideEditBill('rent'));await page.locator('#billAmount').fill('901.25');await page.evaluate(()=>window.checkstrideSubmitBill());await page.waitForFunction(()=>document.getElementById('cloudStatus').textContent.includes('backup failed'));assert.equal(backend.records.A.bills[0].amount,800);await click(page,'[data-page="more"]');await click(page,'[data-more-destination="account"]');const download=page.waitForEvent('download');await click(page,'#downloadRecoveryCopies');assert.equal((await download).suggestedFilename(),'checkstride-recovery.json');page.once('dialog',d=>d.dismiss());await click(page,'#logout');assert.ok(await page.locator('#appView').isVisible());assert.ok(await page.evaluate(()=>localStorage.getItem('checkstride_rest_session')));
}));
