const test=require('node:test'),assert=require('node:assert/strict');
const {chromium,webkit}=require('playwright');
const {serve,mock}=require('./browser-harness.cjs');
for(const [name,engine,viewport] of [['chromium-small',chromium,{width:320,height:568}],['chromium-large',chromium,{width:430,height:932}],['webkit-iphone',webkit,{width:390,height:844}]])test(name+' mocked authenticated mobile flow',async()=>{
 const {server,url}=await serve();let browser;try{browser=await engine.launch({headless:true});const context=await browser.newContext({viewport,isMobile:true,hasTouch:true,serviceWorkers:'block'});const mockApi=await mock(context);const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url);await page.locator('#email').fill('a@example.test');await page.locator('#password').fill('fake-test-password');await page.locator('#authSubmit').click();await page.locator('#appView').waitFor({state:'visible'});
 for(const tab of ['bills','coach','more','home']){await page.locator(`[data-page="${tab}"]`).click();assert.equal(await page.locator(`[data-page="${tab}"]`).getAttribute('class'),'active');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 await page.evaluate(()=>window.checkstrideEditBill('rent'));await page.locator('#billAmount').fill('810.25');await page.evaluate(()=>window.checkstrideSubmitBill());
 await page.evaluate(()=>window.checkstrideEditBill('rent'));await page.waitForTimeout(120);assert.ok(await page.locator('#billAmount').isVisible());await page.locator('#billAmount').fill('820.75');await page.evaluate(()=>window.checkstrideSubmitBill());
 await page.waitForFunction(()=>document.getElementById('cloudStatus').textContent==='Saved');assert.equal(mockApi.records.A.bills[0].amount,820.75);
 await page.reload();await page.locator('#appView').waitFor({state:'visible'});assert.ok((await page.locator('body').innerText()).includes('Rent'));
 mockApi.setFail(true);await page.evaluate(()=>window.checkstrideEditBill('rent'));await page.locator('#billAmount').fill('830.25');await page.evaluate(()=>window.checkstrideSubmitBill());await page.waitForFunction(()=>document.getElementById('cloudStatus').textContent.includes('paused'));assert.ok(await page.evaluate(()=>localStorage.getItem('checkstride_pending_v1:A')));
 mockApi.setFail(false);await page.reload();await page.locator('#appView').waitFor({state:'visible'});await page.waitForFunction(()=>document.getElementById('cloudStatus').textContent==='Saved');assert.equal(mockApi.records.A.bills[0].amount,830.25);
 await page.locator('[data-page="more"]').click();await page.evaluate(()=>document.getElementById('logout').click());await page.locator('#authView').waitFor({state:'visible'});assert.equal(await page.evaluate(()=>localStorage.getItem('checkstride_rest_session')),null);
 await page.locator('#email').fill('b@example.test');await page.locator('#password').fill('fake-test-password');await page.locator('#authSubmit').click();await page.locator('#appView').waitFor({state:'visible'});await page.locator('[data-page="bills"]').click();assert.ok((await page.locator('body').innerText()).includes('B bill'));assert.ok(!(await page.locator('body').innerText()).includes('Rent'));await page.evaluate(()=>document.getElementById('logout').click());await page.locator('#authView').waitFor({state:'visible'});await page.locator('#email').fill('a@example.test');await page.locator('#password').fill('fake-test-password');await page.locator('#authSubmit').click();await page.locator('#appView').waitFor({state:'visible'});await page.locator('[data-page="bills"]').click();assert.ok((await page.locator('body').innerText()).includes('Rent'));assert.ok(!(await page.locator('body').innerText()).includes('B bill'));assert.deepEqual(errors,[]);await context.close();
 }finally{await browser?.close();await new Promise(r=>server.close(r))}
});
