const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const {chromium}=require('playwright');const {serve}=require('./browser-harness.cjs');
test('manifest PNG sizes, scoped caches, service worker and offline public shell',async()=>{
 const manifest=JSON.parse(fs.readFileSync('manifest.webmanifest'));assert.equal(manifest.start_url,'./');assert.equal(manifest.scope,'./');for(const size of [192,512]){const icon=manifest.icons.find(x=>x.sizes===`${size}x${size}`);assert.ok(icon);const png=fs.readFileSync(icon.src.slice(2));assert.equal(png.readUInt32BE(16),size);assert.equal(png.readUInt32BE(20),size)}assert.ok(fs.readFileSync('index.html','utf8').includes('rel="apple-touch-icon"'));
 const {server,url}=await serve();const browser=await chromium.launch({headless:true});try{const context=await browser.newContext();await context.route('https://**/*',route=>route.abort());const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.evaluate(async()=>{await caches.open('unrelated-app-cache');await navigator.serviceWorker.ready});await page.reload();await page.waitForFunction(()=>!!navigator.serviceWorker.controller);const keys=await page.evaluate(()=>caches.keys());assert.ok(keys.includes('unrelated-app-cache'));assert.ok(keys.includes('checkstride-shell-v10'));const cached=await page.evaluate(async()=>{const c=await caches.open('checkstride-shell-v10');return(await c.keys()).map(x=>x.url)});assert.ok(cached.every(x=>x.startsWith(locationOrigin(url))));assert.ok(cached.some(x=>x.endsWith('/cloud-sync.js')));assert.ok(!cached.some(x=>/googleapis|users\//.test(x)));await context.setOffline(true);await page.reload();await page.locator('#authView').waitFor({state:'visible'});assert.ok(await page.locator('#authSubmit').isVisible());await page.evaluate(()=>{localStorage.setItem('checkstride_rest_session',JSON.stringify({localId:'A',refreshToken:'fake-offline-token',email:'a@example.test'}));localStorage.setItem('checkstride_pending_v1:A',JSON.stringify({base:'v0',data:{bills:[{name:'Offline test bill',amount:1}]}}))});await page.reload();await page.locator('#loadingRetry').waitFor({state:'visible'});assert.ok(!(await page.locator('#appView').isVisible()));await page.locator('#loadingSignIn').click();await page.locator('#authView').waitFor({state:'visible'});assert.ok(await page.evaluate(()=>localStorage.getItem('checkstride_pending_v1:A')));assert.deepEqual(errors,[]);
 }finally{await browser.close();await new Promise(r=>server.close(r))}
});
function locationOrigin(url){return new URL(url).origin}

test('successful navigation refreshes the offline HTML cache with the response',async()=>{
 const vm=require('node:vm'),handlers={},puts=[];let pending;
 const response=new Response('<html>updated shell</html>',{status:200,headers:{'Content-Type':'text/html'}});
 vm.runInNewContext(fs.readFileSync('service-worker.js','utf8'),{self:{location:{origin:'https://example.test'},addEventListener:(name,fn)=>handlers[name]=fn},URL,fetch:async()=>response,caches:{open:async()=>({put:async(...args)=>{assert.equal(args.length,2);assert.ok(args[1] instanceof Response);puts.push([args[0],await args[1].text()])}})}});
 handlers.fetch({request:{method:'GET',url:'https://example.test/Checkstride/',mode:'navigate'},respondWith:p=>pending=p});
 assert.equal(await pending,response);await new Promise(r=>setImmediate(r));assert.deepEqual(puts,[['./index.html','<html>updated shell</html>']]);
});
